### ISSUE TITLE
Exception when looking up particular strings in MapDoubleArray

### ISSUE THREAD

**Issue by amake** [takawitter/trie4j#22]
The following produces an `ArrayIndexOutOfBoundsException`:

```
MapPatriciaTrie<Object> mpt = new MapPatriciaTrie<>();
mpt.insert("FOO");
mpt.get("F");
mpt.get("f");

MapDoubleArray<Object> mda = new MapDoubleArray<>(mpt);
mda.get("F");
mda.get("f"); // exception here
```
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at org.trie4j.bv.BytesRank1OnlySuccinctBitVector.isOne(BytesRank1OnlySuccinctBitVector.java:90)
	at org.trie4j.bv.BytesRank1OnlySuccinctBitVector.get(BytesRank1OnlySuccinctBitVector.java:80)
	at org.trie4j.doublearray.DoubleArray.getTermId(DoubleArray.java:243)
	at org.trie4j.AbstractTermIdMapTrie.get(AbstractTermIdMapTrie.java:141)
```

I would expect this to simply return `null` rather than throw an exception. My use case is (natural-language) dictionary lookup with mixed-case keys.

**Comment by takawitter** [comment]
Thanks Aaron,

Which version did you use?
I tested your code with 0.9.2 and got no error (mda.get("f") returns null).

**Comment by amake** [comment]
My apologies, it was 0.9.1. I updated to 0.9.2 and the issue seems to be resolved.

Thanks!
